### ISSUE TITLE
Allow configuration of podcast sorting order

### ISSUE THREAD

**Issue by MrCondescending** [MrCondescending/norsesonic#3]
## Problem description

Out of the box, Airsonic orders all podcast episodes in reverse chronological order. This is useful if you want to listen to the most recent episode of a long-running podcast; it's much less useful if you want to listen to several episodes, or the entire run, of a podcast that has some sort of ordered narrative or uses multi-part episodes (which is almost all of the podcasts I listen to).

This ordering is hardcoded and the only way around it seems to be to either patch Airsonic, or generate a custom feed XML file for each podcast with the timestamps reversed and load that instead of the real feed.

### Steps to reproduce

    1.)Add a podcast.
    2.)Wait for it to parse the feed and download the episodes.
    3.)Observe that the episodes are in r-chronological order.
   4.)Click "play" and observe that episodes are added to the queue in r-c order.
    5.)Click "podcast settings" and observe that there is no way to change this.

## System information

 * **Airsonic version**: 10.1.2-RELEASE – July 28, 2018
 * **Operating system**: N/A
 * **Proxy server**: N/A
 * **Client**: *Chrome

## Additional notes

This ordering is implemented in PodcastService.refreshEpisodes and in PodcastDao.getEpisodes.

**Comment by OGoodness** [comment]
Changed the input for podcast links. They now must contain a .xml somewhere in the URL.

Also, edited the sorting of the podcasts, the user can now sort by clicking on the table headers of the podcast table.


**Files edited:**  

norsesonic\airsonic-main\src\main\webapp\WEB-INF\jsp\podcastChannel.jsp   (Sort-able tables)

norsesonic\airsonic-main\src\main\webapp\WEB-INF\jsp\podcastChannels.jsp  (URL entry)



![image](https://user-images.githubusercontent.com/17714003/53416020-93e01e80-39a0-11e9-8c95-59ea915225cf.png)
