### ISSUE TITLE
Version	(Unknown) – (Unknown) when visiting about page.

### ISSUE THREAD

**Issue by Kenchava** [MrCondescending/norsesonic#6]
## Problem description

Version reports unknown on about page and throws NullPointerException in debug.

### Steps to reproduce

*Describe how somebody else could observe the same behavior you do. If possible,
include relevant configuration or files that cause the problem. If sharing media
files, ensure you are legally permitted to share copies!*

1. Visit about page

## System information

 * **Airsonic version**: IDK it dun broke
 * **Operating system**: Win 10 Home 1803 17134.523
 * **Proxy server**: None
 * **Client**: Chrome 71.0.3578.98 (Official Build) (64-bit) (cohort: Stable)

**Comment by MrCondescending** [comment]
![airsonicabout](https://user-images.githubusercontent.com/7027068/51955233-211b6c00-2411-11e9-9b57-ddf1e8887663.PNG)

This issue is inconsistent between users, but it caused by a NullPointer in VersionService.

```2019-01-29 21:55:45.546  WARN --- o.a.p.service.VersionService             : Failed to resolve local Airsonic version.```

**Comment by Kenchava** [comment]
Removed web dependency for version checking. The issue has been fixed.
